mqtt:
  host: "192.168.0.147"
  port: 1883
  tls: false
  username: "jeedom"
  password: "0Ta9jUaIdFO8R1kFXPyeKCpLdmJeIJWi3mjV3bEi6B7psBBPw2QySBLjHhKl4mJV"
  topic_prefix: "pv"

# Modbus register example for Deye SUN-xK-SG04LP3-EU
schema:
- name: solax_x1_g4
  readings:
  - name: "System State"
    topic: "system/state"
    register: 9
    length: 1
    signed: 0
    substract: 0
    divide: 1
    typereg: "Input"
  - name: "System Use Mode"
    topic: "system/usemode"
    register: 139
    length: 1
    signed: 0
    substract: 0
    divide: 1
    typereg: "holding"
  - name: "To grid energytotal"
    topic: "system/totals/grid_feedin"
    register: 72
    length: 2
    substract: 0
    decimals: 1
    divide: 100
    typereg: "Input"
  - name: "From grid energy total"
    topic: "system/totals/grid_energy"
    register: 74
    length: 2
    substract: 0
    decimals: 1
    divide: 100
    typereg: "Input"
  - name: "Yield total"
    topic: "system/totals/yield"
    register: 82
    length: 2
    substract: 0
    decimals: 1
    divide: 10
    typereg: "Input"
  - name: "Grid yield Today"
    topic: "grid/today/yield"
    register: 80
    length: 2
    substract: 0
    decimals: 1
    divide: 10
    typereg: "Input"
  - name: "Grid Sold Today"
    topic: "grid/today/sold"
    register: 152
    length: 2
    substract: 0
    decimals: 1
    divide: 100
    typereg: "Input"
  - name: "Grid Bought Today"
    topic: "grid/today/bought"
    register: 154
    length: 2
    substract: 0
    decimals: 1
    divide: 100
    typereg: "Input"
  - name: "Grid Frequency"
    topic: "grid/frequency"
    register: 7
    length: 1
    substract: 0
    decimals: 0
    divide: 100
    typereg: "Input"
  - name: "Grid L1 Power"
    topic: "grid/now/l1/power"
    register: 70
    length: 1
    substract: 0
    decimals: 0
    signed: 1
    divide: 1
    typereg: "Input"
  - name: "Grid L1 Volt"
    topic: "grid/now/l1/volt"
    register: 0
    length: 1
    substract: 0
    decimals: 1
    divide: 10
    typereg: "Input"
  - name: "Load Power L1"
    topic: "load/now/l1/power"
    register: 2
    length: 1
    substract: 0
    decimals: 0
    signed: 1
    divide: 1
    typereg: "Input"
  - name: "Load Voltage L1"
    topic: "load/now/l1/volt"
    register: 0
    length: 1
    substract: 0
    decimals: 1
    divide: 10
    typereg: "Input"
  - name: "PV Production Today"
    topic: "pv/today"
    register: 150
    length: 1
    substract: 0
    decimals: 1
    divide: 10
    typereg: "Input"
  - name: "PV String 1 Power"
    topic: "pv/string/1/power"
    register: 10
    length: 1
    substract: 0
    divide: 1
    typereg: "Input"
  - name: "PV String 2 Power"
    topic: "pv/string/2/power"
    register: 11
    length: 1
    substract: 0
    divide: 1
    typereg: "Input"
  - name: "Battery SOC"
    topic: "battery/soc"
    register: 28
    length: 1
    substract: 0
    divide: 1
    typereg: "Input"
  - name: "Battery Charged Today"
    topic: "battery/today/charged"
    register: 35
    length: 1
    substract: 0
    decimals: 1
    divide: 10
    typereg: "Input"
  - name: "Battery Discharged Today"
    topic: "battery/today/discharged"
    register: 32
    length: 1
    substract: 0
    divide: 10
    typereg: "Input"
  - name: "Battery Temperature"
    topic: "battery/temperature"
    register: 24
    length: 1
    substract: 0
    decimals: 1
    divide: 1
    typereg: "Input"
  - name: "Battery Voltage"
    topic: "battery/volt"
    register: 20
    length: 1
    substract: 0
    decimals: 2
    divide: 10
    typereg: "Input"
  - name: "Battery Output Power"
    topic: "battery/power"
    register: 22
    length: 1
    signed: 1
    substract: 0
    decimals: 0
    divide: 1
    typereg: "Input"
  - name: "Battery Output Current"
    topic: "battery/current"
    register: 21
    length: 1
    signed: 1
    substract: 0
    decimals: 2
    divide: 10
    typereg: "Input"

sources:
- name: "Solax X1"
  host: "192.168.0.87"
  port: 502
  schema: solax_x1_g4
  topic_prefix: "x1"
